openapi: 3.0.3
info:
  title: 'ì©¡ëŒ€ë¦¬ Todo App'
  description: 'ì•ˆë…•í•˜ì„¸ìš”?! ì˜¤ëŠ˜ë„ ë¹¡ì½”ë”© í•˜ê³  ê³„ì‹ ê°€ìš”? ë³¸ api ëŠ” ì—°ìŠµìš© api ì…ë‹ˆë‹¤! í˜„ì¬ ë²„ì „ì€ [v1] ì…ë‹ˆë‹¤.'
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:8000'
paths:
  /api/v1/todos:
    get:
      summary: 'Get a list of posts'
      description: "í¬ìŠ¤íŠ¸ ë¦¬ìŠ¤íŠ¸ ê°€ì ¸ì˜¤ê¸°\n<aside class=\"notice\">We mean it; you really should.ğŸ˜•</aside>"
      parameters:
        -
          in: query
          name: page
          description: í˜ì´ì§€
          example: 1
          required: false
          schema:
            type: integer
            description: í˜ì´ì§€
            example: 1
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses:
        200:
          description: ì„±ê³µ
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 52
                      title: 'ì•ˆë…•í•˜ì„¸ìš”? - ì˜ˆì‹œì…ë‹ˆë‹¤'
                      content: í•˜í•˜í•˜í•˜
                      deadline: '2021-12-12'
                      isDone: 52
                      updated_at: '4 hours ago ì „ì— ìˆ˜ì •ë˜ì—ˆìŠµë‹ˆë‹¤.'
                    -
                      id: 51
                      title: 'ì•ˆë…•í•˜ì„¸ìš”?'
                      content: í•˜í•˜í•˜
                      deadline: 'ë§ˆê°ê¸°í•œì´ ì •í•´ì ¸ ìˆì§€ ì•ŠìŠµë‹ˆë‹¤.'
                      isDone: 51
                      updated_at: '4 hours ago ì „ì— ìˆ˜ì •ë˜ì—ˆìŠµë‹ˆë‹¤.'
                    -
                      id: 2
                      title: Reprehenderit.
                      content: 'Quisquam ipsa dignissimos qui ea ut quis maiores. Sit velit deleniti at est.'
                      deadline: 'ë§ˆê°ê¸°í•œì´ ì •í•´ì ¸ ìˆì§€ ì•ŠìŠµë‹ˆë‹¤.'
                      isDone: 2
                      updated_at: '4 hours ago ì „ì— ìˆ˜ì •ë˜ì—ˆìŠµë‹ˆë‹¤.'
                    -
                      id: 3
                      title: Eum.
                      content: 'Cum blanditiis voluptas est molestiae ex. Maiores est omnis labore nam atque.'
                      deadline: 'ë§ˆê°ê¸°í•œì´ ì •í•´ì ¸ ìˆì§€ ì•ŠìŠµë‹ˆë‹¤.'
                      isDone: 3
                      updated_at: '4 hours ago ì „ì— ìˆ˜ì •ë˜ì—ˆìŠµë‹ˆë‹¤.'
                    -
                      id: 4
                      title: 'Iste quae.'
                      content: 'Aut voluptatibus voluptates cum nulla. Eos id et reiciendis numquam placeat.'
                      deadline: 'ë§ˆê°ê¸°í•œì´ ì •í•´ì ¸ ìˆì§€ ì•ŠìŠµë‹ˆë‹¤.'
                      isDone: 4
                      updated_at: '4 hours ago ì „ì— ìˆ˜ì •ë˜ì—ˆìŠµë‹ˆë‹¤.'
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 11
                    path: 'http://127.0.0.1:8000/api/v1/todos'
                    per_page: 5
                    to: 5
                    total: 51
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 52
                        title: 'ì•ˆë…•í•˜ì„¸ìš”? - ì˜ˆì‹œì…ë‹ˆë‹¤'
                        content: í•˜í•˜í•˜í•˜
                        deadline: '2021-12-12'
                        isDone: 52
                        updated_at: '4 hours ago ì „ì— ìˆ˜ì •ë˜ì—ˆìŠµë‹ˆë‹¤.'
                      -
                        id: 51
                        title: 'ì•ˆë…•í•˜ì„¸ìš”?'
                        content: í•˜í•˜í•˜
                        deadline: 'ë§ˆê°ê¸°í•œì´ ì •í•´ì ¸ ìˆì§€ ì•ŠìŠµë‹ˆë‹¤.'
                        isDone: 51
                        updated_at: '4 hours ago ì „ì— ìˆ˜ì •ë˜ì—ˆìŠµë‹ˆë‹¤.'
                      -
                        id: 2
                        title: Reprehenderit.
                        content: 'Quisquam ipsa dignissimos qui ea ut quis maiores. Sit velit deleniti at est.'
                        deadline: 'ë§ˆê°ê¸°í•œì´ ì •í•´ì ¸ ìˆì§€ ì•ŠìŠµë‹ˆë‹¤.'
                        isDone: 2
                        updated_at: '4 hours ago ì „ì— ìˆ˜ì •ë˜ì—ˆìŠµë‹ˆë‹¤.'
                      -
                        id: 3
                        title: Eum.
                        content: 'Cum blanditiis voluptas est molestiae ex. Maiores est omnis labore nam atque.'
                        deadline: 'ë§ˆê°ê¸°í•œì´ ì •í•´ì ¸ ìˆì§€ ì•ŠìŠµë‹ˆë‹¤.'
                        isDone: 3
                        updated_at: '4 hours ago ì „ì— ìˆ˜ì •ë˜ì—ˆìŠµë‹ˆë‹¤.'
                      -
                        id: 4
                        title: 'Iste quae.'
                        content: 'Aut voluptatibus voluptates cum nulla. Eos id et reiciendis numquam placeat.'
                        deadline: 'ë§ˆê°ê¸°í•œì´ ì •í•´ì ¸ ìˆì§€ ì•ŠìŠµë‹ˆë‹¤.'
                        isDone: 4
                        updated_at: '4 hours ago ì „ì— ìˆ˜ì •ë˜ì—ˆìŠµë‹ˆë‹¤.'
                    items:
                      type: object
                  meta:
                    type: object
                    example:
                      current_page: 1
                      from: 1
                      last_page: 11
                      path: 'http://127.0.0.1:8000/api/v1/todos'
                      per_page: 5
                      to: 5
                      total: 51
      tags:
        - 'í¬ìŠ¤íŠ¸ ê´€ë¦¬'
      security: []
    post:
      summary: 'add a new todo'
      description: "í¬ìŠ¤íŠ¸ ì¶”ê°€í•˜ê¸°\n<aside class=\"notice\">We mean it; you really should.ğŸ˜•</aside>"
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses:
        201:
          description: 'ë§ˆê°ê¸°í•œì´ ì •í•´ì ¸ ìˆì§€ ì•Šì„ ë•Œ'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 50
                    title: 'ë¹¨ë˜í•˜ê¸°. - ì˜ˆì‹œ'
                    content: 'ë¹¨ë˜ëŒë¦´ë•Œ ìˆ˜ê±´ ë¨¼ì € ëŒë¦¬ê¸° - ì˜ˆì‹œ'
                    deadline: 'ë§ˆê°ê¸°í•œì´ ì •í•´ì ¸ìˆì§€ ì•ŠìŠµë‹ˆë‹¤.'
                    isDone: ì™„ë£Œ
                    create_at: '15 hours ago ì „ì— ì‘ì„±ë˜ì—ˆë‹¤.'
                properties:
                  data:
                    type: object
                    example:
                      id: 50
                      title: 'ë¹¨ë˜í•˜ê¸°. - ì˜ˆì‹œ'
                      content: 'ë¹¨ë˜ëŒë¦´ë•Œ ìˆ˜ê±´ ë¨¼ì € ëŒë¦¬ê¸° - ì˜ˆì‹œ'
                      deadline: 'ë§ˆê°ê¸°í•œì´ ì •í•´ì ¸ìˆì§€ ì•ŠìŠµë‹ˆë‹¤.'
                      isDone: ì™„ë£Œ
                      create_at: '15 hours ago ì „ì— ì‘ì„±ë˜ì—ˆë‹¤.'
        422:
          description: 'ë°ì´í„°ê°€ ìœ íš¨í•˜ì§€ ì•Šì„ ë•Œ'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The given data was invalid.'
                  errors:
                    deadline:
                      - 'The deadline is not a valid date.'
                properties:
                  message:
                    type: string
                    example: 'The given data was invalid.'
                  errors:
                    type: object
                    example:
                      deadline:
                        - 'The deadline is not a valid date.'
      tags:
        - 'í¬ìŠ¤íŠ¸ ê´€ë¦¬'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'í• ì¼ ì œëª©'
                  example: 'ì±… ì½ê¸°'
                content:
                  type: longText
                  description: 'í• ì¼ ë‚´ìš©.'
                  example: 'ìê¸°ê°œë°œì— ëŒ€í•œ ì±…ì„ ì½ì'
                deadline:
                  type: date
                  description: ë§ˆê°ê¸°í•œ
                  example: null
                isDone:
                  type: boolean
                  description: ì™„ë£Œì—¬ë¶€
                  example: true
              required:
                - title
                - isDone
      security: []
  '/api/v1/todos/{id}':
    get:
      summary: 'get a todo'
      description: "íŠ¹ì • í• ì¼ ê°€ì ¸ì˜¤ê¸°\n\n<aside class=\"notice\">urlParam ì— ëŒ€í•œ ì„¤ëª…</aside>"
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses:
        200:
          description: 'ë§ˆê°ê¸°í•œì´ ì •í•´ì ¸ ìˆì§€ ì•Šì„ë•Œ'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 50
                    title: 'ë¹¨ë˜í•˜ê¸°. - ì˜ˆì‹œ'
                    content: 'ë¹¨ë˜ëŒë¦´ë•Œ ìˆ˜ê±´ ë¨¼ì € ëŒë¦¬ê¸° - ì˜ˆì‹œ'
                    deadline: 'ë§ˆê°ê¸°í•œì´ ì •í•´ì ¸ìˆì§€ ì•ŠìŠµë‹ˆë‹¤.'
                    isDone: ì™„ë£Œ
                    create_at: '15 hours ago ì „ì— ì‘ì„±ë˜ì—ˆë‹¤.'
                properties:
                  data:
                    type: object
                    example:
                      id: 50
                      title: 'ë¹¨ë˜í•˜ê¸°. - ì˜ˆì‹œ'
                      content: 'ë¹¨ë˜ëŒë¦´ë•Œ ìˆ˜ê±´ ë¨¼ì € ëŒë¦¬ê¸° - ì˜ˆì‹œ'
                      deadline: 'ë§ˆê°ê¸°í•œì´ ì •í•´ì ¸ìˆì§€ ì•ŠìŠµë‹ˆë‹¤.'
                      isDone: ì™„ë£Œ
                      create_at: '15 hours ago ì „ì— ì‘ì„±ë˜ì—ˆë‹¤.'
        404:
          description: 'todo not found'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'í•´ë‹¹ í• ì¼ì„ ì°¾ì„ ìˆ˜ê°€ ì—†ìŠµë‹ˆë‹¤.'
                properties:
                  message:
                    type: string
                    example: 'í•´ë‹¹ í• ì¼ì„ ì°¾ì„ ìˆ˜ê°€ ì—†ìŠµë‹ˆë‹¤.'
      tags:
        - 'í¬ìŠ¤íŠ¸ ê´€ë¦¬'
      security: []
    put:
      summary: 'Update a todo'
      description: "íŠ¹ì • í• ì¼ ìˆ˜ì •í•˜ê¸°\n<aside class=\"notice\">We mean it; you really should.ğŸ˜•</aside>"
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 54
                    title: 'ìƒˆ í• ì¼'
                    content: 'ì €ë… ì¥ë³´ê¸°'
                    deadline: '2021-12-01'
                    isDone: ë¯¸ì™„ë£Œ
                    create_at: '1 second ago ì „ì— ì‘ì„±ë˜ì—ˆë‹¤.'
                properties:
                  data:
                    type: object
                    example:
                      id: 54
                      title: 'ìƒˆ í• ì¼'
                      content: 'ì €ë… ì¥ë³´ê¸°'
                      deadline: '2021-12-01'
                      isDone: ë¯¸ì™„ë£Œ
                      create_at: '1 second ago ì „ì— ì‘ì„±ë˜ì—ˆë‹¤.'
        404:
          description: 'todo not found'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'í•´ë‹¹ í• ì¼ì„ ì°¾ì„ ìˆ˜ê°€ ì—†ìŠµë‹ˆë‹¤.'
                properties:
                  message:
                    type: string
                    example: 'í•´ë‹¹ í• ì¼ì„ ì°¾ì„ ìˆ˜ê°€ ì—†ìŠµë‹ˆë‹¤.'
        422:
          description: 'ë°ì´í„°ê°€ ìœ íš¨í•˜ì§€ ì•Šì„ ë•Œ'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The given data was invalid.'
                  errors:
                    deadline:
                      - 'The deadline is not a valid date.'
                properties:
                  message:
                    type: string
                    example: 'The given data was invalid.'
                  errors:
                    type: object
                    example:
                      deadline:
                        - 'The deadline is not a valid date.'
      tags:
        - 'í¬ìŠ¤íŠ¸ ê´€ë¦¬'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'í• ì¼ ì œëª©'
                  example: 'ì±… ì½ê¸°'
                content:
                  type: longText
                  description: 'í• ì¼ ë‚´ìš©.'
                  example: 'ìê¸°ê°œë°œì— ëŒ€í•œ ì±…ì„ ì½ì'
                deadline:
                  type: date
                  description: ë§ˆê°ê¸°í•œ
                  example: null
                isDone:
                  type: boolean
                  description: ì™„ë£Œì—¬ë¶€
                  example: true
              required:
                - title
                - isDone
      security: []
    delete:
      summary: 'Remove a todo'
      description: "íŠ¹ì • í• ì¼ ì‚­ì œí•˜ê¸°\n<aside class=\"notice\">We mean it; you really should.ğŸ˜•</aside>"
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
      responses:
        204:
          description: success
        404:
          description: 'todo not found'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'í•´ë‹¹ í• ì¼ì„ ì°¾ì„ ìˆ˜ê°€ ì—†ìŠµë‹ˆë‹¤.'
                properties:
                  message:
                    type: string
                    example: 'í•´ë‹¹ í• ì¼ì„ ì°¾ì„ ìˆ˜ê°€ ì—†ìŠµë‹ˆë‹¤.'
      tags:
        - 'í¬ìŠ¤íŠ¸ ê´€ë¦¬'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'í• ì¼ ì•„ì´ë””'
        example: 10
        required: true
        schema:
          type: integer
tags:
  -
    name: 'í¬ìŠ¤íŠ¸ ê´€ë¦¬'
    description: "\nAPIs for managing posts\ní¬ìŠ¤íŠ¸ë¥¼ ê´€ë¦¬í•©ë‹ˆë‹¤."
